"""add_video_reactions_table

Revision ID: 6c7d8e9f0a1b
Revises: 5a00582501dd
Create Date: 2025-01-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c7d8e9f0a1b'
down_revision: Union[str, None] = '5a00582501dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_reactions',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['linap.users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['linap.videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_reaction'),
    schema='linap'
    )
    op.create_index('idx_video_reactions_user', 'video_reactions', ['user_id'], schema='linap')
    op.create_index('idx_video_reactions_video', 'video_reactions', ['video_id'], schema='linap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_reactions_video', table_name='video_reactions', schema='linap')
    op.drop_index('idx_video_reactions_user', table_name='video_reactions', schema='linap')
    op.drop_table('video_reactions', schema='linap')
    # ### end Alembic commands ###
